spring.application.name=stock_fetcher_service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fetcher_db?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update
finnhub.api.key=${FINNHUB_API_KEY:changeme}
