spring.application.name=stock_analysis_service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/analysis_db?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update

fetcher.service.url=${FETCHER_SERVICE_URL:http://localhost:8081/stocks/fetch/}
