spring.application.name=stock_pattern_service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/pattern_db?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update

analysis.service.url=${ANALYSIS_SERVICE_URL:http://localhost:8082/analysis/}
