spring.application.name=stock_api_gateway
server.port=8080
spring.cloud.gateway.routes[0].id=fetcher
spring.cloud.gateway.routes[0].uri=${FETCHER_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/stocks/**

spring.cloud.gateway.routes[1].id=analysis
spring.cloud.gateway.routes[1].uri=${ANALYSIS_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/analysis/**

spring.cloud.gateway.routes[2].id=pattern
spring.cloud.gateway.routes[2].uri=${PATTERN_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/patterns/**

fetcher.url=${FETCHER_URL:http://localhost:8081}
analysis.url=${ANALYSIS_URL:http://localhost:8082}
pattern.url=${PATTERN_URL:http://localhost:8083}
